/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tj3f4N0O3WY
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export function SearchBar() {
  return (
    <div className="max-w-4xl mx-auto p-4">
      <div className="flex items-center space-x-2 bg-white p-4 rounded-lg shadow">
        <SearchIcon className="text-gray-400" />
        <Input
          className="flex-1"
          placeholder="Search listings..."
          type="text"
        />
        <Button className="space-x-1" variant="outline">
          <SlidersIcon className="text-gray-400" />
        </Button>
      </div>
      <div className="mt-4">
        <h3 className="text-sm font-semibold text-gray-600 mb-2">
          Mots-clés récemment utilisés
        </h3>
        <div className="flex space-x-2">
          <Badge className="bg-[#e0f2fe] text-[#0284c7]" variant="secondary">
            #rolex
          </Badge>
          <Badge className="bg-[#fee2e2] text-[#b91c1c]" variant="secondary">
            #patek_philipe
          </Badge>
          <Badge className="bg-[#ccfbf1] text-[#0d9488]" variant="secondary">
            #or
          </Badge>
          <Badge className="bg-[#e9d5ff] text-[#7e22ce]" variant="secondary">
            #argent
          </Badge>
          <Badge className="bg-[#c7d2fe] text-[#3730a3]" variant="secondary">
            #13600
          </Badge>
          <Badge className="bg-[#fecaca] text-[#b91c1c]" variant="secondary">
            #daytona
          </Badge>
        </div>
      </div>
    </div>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function SlidersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="4" y1="21" y2="14" />
      <line x1="4" x2="4" y1="10" y2="3" />
      <line x1="12" x2="12" y1="21" y2="12" />
      <line x1="12" x2="12" y1="8" y2="3" />
      <line x1="20" x2="20" y1="21" y2="16" />
      <line x1="20" x2="20" y1="12" y2="3" />
      <line x1="2" x2="6" y1="14" y2="14" />
      <line x1="10" x2="14" y1="8" y2="8" />
      <line x1="18" x2="22" y1="16" y2="16" />
    </svg>
  );
}
